corsi_formazione/urls.py
from django.urls import path
from corsi_formazione.views import indexCorsi,view_a,view_b,view_c,view_d,view_e,view_f

app_name = 'corsi_formazione'

#urlpatterns di tutte le view
urlpatterns=[
    path('indexCorsi',indexCorsi, name="indexCorsi"),
    path('view_a',view_a, name="view_a"),
    path('view_b',view_b, name="view_b"),
    path('view_b/<int:pk>',view_b, name="view_b"),
    path('view_c',view_c, name="view_c"),
    path('view_d',view_d, name="view_d"),
    path('view_e',view_e, name="view_e"),
    path('view_f',view_f, name="view_f"),
]

news/urls.py
from django.urls import path
from news.views import home, articoloDetailView, listaArticoli,queryBase,giornalistaDetailView,index_root,index

app_name = 'news'

urlpatterns=[
    path('',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("queryBase", queryBase, name="queryBase"),
    path('index',index, name="index"),
    path('index_root',index_root, name="index_root"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base,name='base'),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti_app/',include("voti_app.urls",namespace="voti")),
    path('eventi_scolastici/',include("eventi_scolastici.urls",namespace="eventi_scolastici")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
]

corsi_formazione/models.py
from django.db import models
from datetime import datetime

# Modello Corso

class Corso(models.Model):
    titolo=models.CharField(max_length=20)
    descrizione=models.TextField()
    data_inizio=models.DateField(default=datetime.now(),blank=True)
    data_fine=models.DateField(default=datetime.now(),blank=True)
    posti_disponibili=models.IntegerField(default=0)

    def __str__(self):
        return self.titolo
    
    class Meta:
        verbose_name = "Corso"
        verbose_name_plural = "Corsi"
    

corsi_formazione/views.py
from django.shortcuts import render,get_object_or_404
from corsi_formazione.models import Corso
import datetime

#view della pagina index
def indexCorsi(request):
    return render(request,"indexCorsi.html")

#view per la pagina che stampa l'elenco corsi per data
def view_a(request):
    elenco_corsi = Corso.objects.order_by('-data_inizio')
    context={"elenco_corsi":elenco_corsi}
    return render(request,"view_a.html",context)

#view per la pagina che stampa i dettagli di un corso
def view_b(request,pk):
    corso = get_object_or_404(Corso, pk=pk)
    context={"corso": corso}
    return render(request,"view_b.html",context)

#view per la pagina che stampa l'elenco dei corsi iniziati dopo il 01/05/2025
def view_c(request):
    elenco_corsi = Corso.objects.filter(data_inizio__gt=datetime.date(2025, 5, 1))
    context={"elenco_corsi":elenco_corsi}
    return render(request,"view_c.html",context)

#view per la pagina che stampa l'elenco dei corsi con almeno 20 posti disp
def view_d(request):
    elenco_corsi = Corso.objects.filter(posti_disponibili__lte=20)
    context={"elenco_corsi":elenco_corsi}
    return render(request,"view_d.html",context)

#view per la pagina che stampa l'elenco dei corsi finiti prima del 30/04/2025
def view_e(request):
    elenco_corsi = Corso.objects.filter(data_fine__lt=datetime.date(2025, 4, 30))
    context={"elenco_corsi":elenco_corsi}
    return render(request,"view_e.html",context)

#view per la pagina che stampa le specifiche avanzate: corso con minor e corso con maggior posti disponibili e somma dei posti disponibili di tutti i corsi
def view_f(request):
    corsoMax=Corso.objects.order_by('-posti_disponibili').first()
    corsoMin=Corso.objects.order_by('posti_disponibili').first()
    
    elenco_corsi=Corso.objects.all()
    tot=0
    for corso in elenco_corsi:
        tot+=corso.posti_disponibili
    
    context={"corsoMax":corsoMax,"corsoMin":corsoMin,"totPosti":tot}
    return render(request,"view_f.html",context)

corsi_formazione/templates/indexCorsi.html
{%extends "base.html"%}
{% block title %} {{block.super}} Index Corsi{% endblock title %}
{%block content%}
    <h1>Benvenuto nel sistema di gestione dei Corsi di Formazione</h1>
    <ul>
        <li><a href="{% url 'corsi_formazione:view_a'%}">Lista dei Corsi</a></li>
        <li><a href="{% url 'corsi_formazione:view_b' 1 %}">Dettagli dei Corsi</a></li>
        <li><a href="{% url 'corsi_formazione:view_c'%}">Corsi che iniziano dopo il 01/05/2025</a></li>
        <li><a href="{% url 'corsi_formazione:view_d'%}">Corsi con meno di 20 posti disponibili</a></li>
        <li><a href="{% url 'corsi_formazione:view_e'%}">Corsi che terminano entro il 30/04/2025</a></li>
        <li><a href="{% url 'corsi_formazione:view_f'%}">Statistiche Avanzate sui Corsi</a></li>
    </ul>
{%endblock content%}

corsi_formazione/templates/view_a.html
{%extends "base.html"%}
{% block title %} 
   Elenco corsi per data
{% endblock title %}

{%block content%}
    <h1>Corsi per data di inizio: </h1>
    {% for corso in elenco_corsi %}
        <ul>
            <strong><li>Titolo:</strong>
                <a href="/corsi_formazione/view_b/{{corso.id}}">{{corso.titolo}}</a>
            </li>
        </ul>
    {% endfor %}
{%endblock content%}

corsi_formazione/templates/view_b.html
{%extends "base.html"%}
{% block title %} 
    {{ corso.titolo }}
{% endblock title %}

{%block content%}
    <h1>{{ corso.titolo }}</h1>
    <h3>{{ corso.descrizione }}</h3>
    <h5>Data di inizio: {{ corso.data_inizio }}</h5>
    <h5>Data di fine: {{ corso.data_fine }}</h5>
    <h5>Posti disponibili: {{ corso.posti_disponibili }}</h5>
{%endblock content%}

corsi_formazione/templates/view_c.html
{%extends "base.html"%}
{% block title %} 
   Elenco corsi dopo il 01/05/2025
{% endblock title %}

{%block content%}
    <h1>Elenco corsi dopo il 01/05/2025: </h1>
    {% for corso in elenco_corsi %}
        <ul>
            <strong><li>Titolo:</strong>
                <a href="/corsi_formazione/view_b/{{corso.id}}">{{corso.titolo}}</a>
            </li>
        </ul>
    {% endfor %}
{%endblock content%}

corsi_formazione/templates/view_d.html
{%extends "base.html"%}
{% block title %} 
Elenco corsi con meno di 20 posti disponibili
{% endblock title %}

{%block content%}
    <h1>Elenco corsi con meno di 20 posti disponibili: </h1>
    {% for corso in elenco_corsi %}
        <ul>
            <strong><li>Titolo:</strong>
                <a href="/corsi_formazione/view_b/{{corso.id}}">{{corso.titolo}}</a>
            </li>
        </ul>
    {% endfor %}
{%endblock content%}

corsi_formazione/templates/view_e.html
{%extends "base.html"%}
{% block title %} 
Corsi che terminano entro il 30/04/2025
{% endblock title %}

{%block content%}
    <h1>Corsi che terminano entro il 30/04/2025: </h1>
    {% for corso in elenco_corsi %}
        <ul>
            <strong><li>Titolo:</strong>
                <a href="/corsi_formazione/view_b/{{corso.id}}">{{corso.titolo}}</a>
            </li>
        </ul>
    {% endfor %}
{%endblock content%}

corsi_formazione/templates/view_f.html
{%extends "base.html"%}
{% block title %} 
Statistiche avanzate sui corsi
{% endblock title %}

{%block content%}
    <h1>Statistiche avanzate: </h1>
    <h5>Corso con il maggior numero di posti disponibili: <a href="/corsi_formazione/view_b/{{corsoMax.id}}">{{corsoMax.titolo}}</a> ({{corsoMax.posti_disponibili}} posti)</h5>
    <h5>Corso con il minor numero di posti disponibili: <a href="/corsi_formazione/view_b/{{corsoMin.id}}">{{corsoMin.titolo}}</a> ({{corsoMin.posti_disponibili}} posti)</h5>
    <h5>Numero totale di posti disponibili per tutti i corsi:{{totPosti}}</h5>           
{%endblock content%}