news/urls.py
from django.urls import path
from news.views import home, articoloDetailView, listaArticoli,queryBase,giornalistaDetailView,index_root,index

app_name = 'news'

urlpatterns=[
    path('',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("queryBase", queryBase, name="queryBase"),
    path('index',index, name="index"),
    path('index_root',index_root, name="index_root"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista, chi_siamo,variabili,index,index_root

app_name="prima_app"
urlpatterns=[
    path('homepage',homepage, name="homepage"),
    path('welcome',welcome, name="welcome"),
    path('lista',lista, name="lista"),
    path('chi_siamo',chi_siamo, name="chi_siamo"),
    path('variabili',variabili, name="variabili"),
    path('index_root',index_root, name="index_root"),
    path('',index, name="index"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base,name='base'),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti_app/',include("voti_app.urls",namespace="voti")),
    path('eventi_scolastici/',include("eventi_scolastici.urls",namespace="eventi_scolastici")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
]

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request,"homepage.html")
def welcome(request):
    return render(request,"welcome.html")
def lista(request):
    return render(request,"lista.html")
def chi_siamo(request):
    return render(request,"chi_siamo.html")
def index(request):
    return render(request,"index.html")
def index_root(request):
    return render(request,"index_root.html")
def variabili(request):
    context={
        'var1': 'Prima variabile',
        'var2': 'Seconda variabile',
        'var3': 'Terza variabile',
    }
    return render(request,"variabili.html",context)

prima_app/templates/chi_siamo.html
{%extends "base.html"%}
{% block title %} {{block.super}} Chi siamo {% endblock title %}

{%block content%}
        <h1>Chi siamo</h1>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
{%endblock content%}

prima_app/templates/homepage.html
{%extends "base.html"%}
{% block title %} {{block.super}} Homepage{% endblock title %}

{%block content%}
        <h1>Benvenuto</h1>
{%endblock content%}

prima_app/templates/index.html
{%extends "base.html"%}
{% block title %} {{block.super}} Index{% endblock title %}
{%block content%}
        <ol>
            <li><a href="{% url 'prima_app:index_root'%}">Index root</a></li>
            <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
            <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
            <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
            <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
            <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
        </ol>
{%endblock content%}

prima_app/templates/lista.html
{%extends "base.html"%}
{% block title %} {{block.super}} Lista{% endblock title %}
{%block content%}
        <ol>
            <li>Primo</li>
            <li>Secondo</li>
            <li>Terzo</li>
        </ol>
{%endblock content%}

prima_app/templates/variabili.html
{%extends "base.html"%}
{% block title %} {{block.super}} Variabili{% endblock title %}
{%block content%}
        <ol>
            <li>{{var1}}</li>
            <li>{{var2}}</li>
            <li>{{var3}}</li>
        </ol>
{%endblock content%}

prima_app/templates/welcome.html
{%extends "base.html"%}
{% block title %} {{block.super}} Welcome{% endblock title %}

{%block content%}
    <h1>Welcome</h1>
{%endblock content%}