forms_app/urls.py
from django.urls import path
from forms_app.views import contatti,lista_contatti,modifica_contatto,elimina_contatto

app_name = 'form_app'

urlpatterns = [
    path('contatti/',contatti,name='contatti'),
    path('lista_contatti/',lista_contatti,name='lista_contatti'),
    path('modifica_contatto/<int:pk>/',modifica_contatto,name='modifica_contatto'),
    path('elimina_contatto/<int:pk>/',elimina_contatto,name='elimina_contatto'),
]

news/urls.py
from django.urls import path
from news.views import home, articoloDetailView, listaArticoli,queryBase,giornalistaDetailView,index_root,index

app_name = 'news'

urlpatterns=[
    path('',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("queryBase", queryBase, name="queryBase"),
    path('index',index, name="index"),
    path('index_root',index_root, name="index_root"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista, chi_siamo,variabili,index,index_root

app_name="prima_app"
urlpatterns=[
    path('homepage',homepage, name="homepage"),
    path('welcome',welcome, name="welcome"),
    path('lista',lista, name="lista"),
    path('chi_siamo',chi_siamo, name="chi_siamo"),
    path('variabili',variabili, name="variabili"),
    path('index_root',index_root, name="index_root"),
    path('',index, name="index"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base,name='base'),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti_app/',include("voti_app.urls",namespace="voti")),
    path('eventi_scolastici/',include("eventi_scolastici.urls",namespace="eventi_scolastici")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if,if_else_elif,index,index_root

app_name="seconda_app"
urlpatterns=[
    path('es_if',es_if,name='es_if'),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('index',index, name="index"),
    path('index_root',index_root, name="index_root"),
]

voti_app/urls.py
from django.urls import path
from voti_app.views import view_a,view_b,view_c,view_d

app_name = 'voti_app'

urlpatterns=[
    path('lista_materie',view_a,name="lista_materie"),
    path('lista_voti',view_b,name="lista_voti"),
    path('media_studenti',view_c,name="media_studenti"),
    path('max_min',view_d,name="max_min"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Primo progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Prima app
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:index'%}">Index</a>
                <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Home page benvenuto</a>
                <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
                <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
                <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
                <div class="dropdown-divider"></div>
              </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Seconda app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">es_if</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">if_else_elif</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   News
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'news:homeview'%}">Home</a>
                  <a class="dropdown-item" href="{% url 'news:articolo_detail' 1 %}">Dettagli articolo</a>
                  <a class="dropdown-item" href="{% url 'news:lista_articoli'%}">Lista Articoli</a>
                  <a class="dropdown-item" href="{% url 'news:queryBase'%}">Query</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>


              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Voti
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'voti:lista_materie'%}">Lista materie</a>
                  <a class="dropdown-item" href="{% url 'voti:lista_voti'%}">Lista voti</a>
                  <a class="dropdown-item" href="{% url 'voti:media_studenti'%}">Media voti studenti</a>
                  <a class="dropdown-item" href="{% url 'voti:max_min'%}">Max e Min</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>



              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Corsi formazione
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'corsi_formazione:indexCorsi'%}">Index</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_a'%}">Corsi in ordine di data di inizio</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_b' 1 %}">Dettagli corso</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_c'%}">Corsi dopo il 01/05/2025</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_d'%}">Corsi con meno di 20 posti disponibili</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_e'%}">Corsi finiti entro il 30/04/2025</a>
                  <a class="dropdown-item" href="{% url 'corsi_formazione:view_f'%}">Statistiche avanzate sui corsi</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{request.user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <div class="dropdown-divider"></div>
                  <form id="logout-form" action="{% url 'logout'%}" method="post">
                    {% csrf_token %}
                    <button class="btn ft-power" type="submit">Logout</button>
                  </form>
                </div>
              </li>
            {%else%}
              <li class="nav-item">
                <a class="nav-link" href="#">Registrati</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login'%}">Login</a>
              </li>
            {%endif%}


          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Contatti
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'forms_app:contatti'%}">Contattaci</a>
              <a class="dropdown-item" href="{% url 'forms_app:lista_contatti'%}">Lista contatti</a>
              <div class="dropdown-divider"></div>
            </div>
          </li>



        </div>
    </nav>


      <div class="container my-4">
        <!-- servirà per inserire i contenuti nella pagina -->
        {%block content%}
        {%endblock content%}
        <!-- servirà per inserire il codice javascript-->
        {%block script%}
        {%endblock script%}
      </div>

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index_root.html
{%extends "base.html"%}
{%block content%}
    <ul>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">index prima app</a></li>
        <li><a href="{% url 'seconda_app:index'%}">index seconda app</a></li>
        <li><a href="{% url 'news:index'%}">index news</a></li>
    <ul>
{%endblock content%}