news/urls.py
from django.urls import path
from news.views import home, articoloDetailView, listaArticoli,queryBase,giornalistaDetailView,index_root,index

app_name = 'news'

urlpatterns=[
    path('',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("queryBase", queryBase, name="queryBase"),
    path('index',index, name="index"),
    path('index_root',index_root, name="index_root"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base,name='base'),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('news/',include("news.urls",namespace="news")),
    path('voti_app/',include("voti_app.urls",namespace="voti")),
    path('eventi_scolastici/',include("eventi_scolastici.urls",namespace="eventi_scolastici")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
]

news/models.py
from django.db import models
from datetime import datetime

class Giornalista(models.Model):
    nome=models.CharField(max_length=20)
    cognome=models.CharField(max_length=20)
    dataNascita=models.DateField(default=datetime.now(),blank=True)

    def __str__(self):
        return self.nome + " " + self.cognome
    
    class Meta:
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"
    
class Articolo(models.Model):
    titolo=models.CharField(max_length=100)
    contenuto=models.TextField()
    giornalista=models.ForeignKey(Giornalista, on_delete=models.CASCADE,related_name="articoli")
    visualizzazioni=models.SmallIntegerField(default=0)
    dataPubblicazione=models.DateField(default=datetime.now(),blank=True)

    def __str__(self):
        return self.titolo
    
    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

news/views.py
from django.shortcuts import render, get_object_or_404
from news.models import Articolo, Giornalista
import datetime


def index(request):
    return render(request,"index3.html")

def index_root(request):
    return render(request,"index_root.html")


def articoloDetailView(request, pk):
    articolo = get_object_or_404(Articolo, pk=pk)
    context={"articolo": articolo}
    return render(request, "articolo_detail.html", context)

def giornalistaDetailView(request,pk):
    giornalista = get_object_or_404(Giornalista, pk=pk)
    articoli = Articolo.objects.filter(giornalista_id=pk)
    context={"giornalista": giornalista, "articoli":articoli}
    return render(request, "giornalista_detail.html", context)

def queryBase(request):
    #1. Tutti gli articoli scritti da giornalisti di un certo cognome:
    articoli_cognome = Articolo.objects.filter(giornalista__cognome='Rossi')
    
    #2. Totale
    numero_totale_articoli = Articolo.objects.count()
    
    #3. Contare il numero di articoli scritti da un giornalista specifico:
    giornalista_1 = Giornalista.objects.get(id=2)
    numero_articoli_giornalista_1 = Articolo.objects.filter(giornalista=giornalista_1).count()
    
    #4. Ordinare gli articoli per numero di visualizzazioni in ordine decrescente:
    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni')
    
    #5. Tutti gli articoli che non hanno visualizzazioni:
    articoli_senza_visualizzazioni = Articolo.objects.filter(visualizzazioni=0)
    
    #6. Articolo più visualizzato:
    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()
    
    #7. Tutti i giornalisti nati dopo una certa data:
    giornalisti_data = Giornalista.objects.filter(dataNascita__gt=datetime.date(1980, 1, 1))
    
    #8. Tutti gli articoli pubblicati in una data specifica:
    articoli_del_giorno = Articolo.objects.filter(dataPubblicazione=datetime.date(2023, 1, 1))
    
    #9. Tutti gli articoli pubblicati in un intervallo di date:
    articoli_periodo = Articolo.objects.filter(dataPubblicazione__range=(datetime.date(2023, 1, 1), datetime.date(2023, 12, 31)))
    
    #10. Gli articoli scritti da giornalisti nati prima del 1980:
    giornalisti_nati = Giornalista.objects.filter(dataNascita__lt=datetime.date(1980, 1, 1))
    articoli_giornalisti = Articolo.objects.filter(giornalista__in=giornalisti_nati)
    
    #11. Il giornalista più giovane:
    giornalista_giovane = Giornalista.objects.order_by('dataNascita').first()
    
    #12. Il giornalista più anziano:
    giornalista_anziano = Giornalista.objects.order_by('-dataNascita').first()
    
    #13. Gli ultimi 5 articoli pubblicati:
    ultimi = Articolo.objects.order_by('-dataPubblicazione')[:5]
    
    #14. Tutti gli articoli con un certo numero minimo di visualizzazioni:
    articoli_minime_visualizzazioni = Articolo.objects.filter(visualizzazioni__gte=100)
    
    #15. Tutti gli articoli che contengono una certa parola nel titolo:
    articoli_parola = Articolo.objects.filter(titolo__icontains='importante')
    
    #16 Articoli pubblicati in un certo mese di un anno specifico:
    #nota per poter modificare la data di un articolo togliere la proprietà auto_now=True al field data nel model
    #o dare i comandi makemigrations e migrate per applicare le modifiche al database
    articoli_mese_anno = Articolo.objects.filter(dataPubblicazione__month=1, dataPubblicazione__year=2023)

    #17 Giornalisti con almeno un articolo con più di 100 visualizzazioni
    giornalisti_con_articoli_popolari = Giornalista.objects.filter(articoli__visualizzazioni__gte=100).distinct()

    #UTILIZZO DI PIÙ CONDIZIONI DI SELEZIONE
    data = datetime.date(1990, 1, 1)
    visualizzazioni = 50
    # Per mettere in AND le condizioni separarle con la virgola
    # 18 ...scrivi quali articoli vengono selezionati
    articoli_con_and = Articolo.objects.filter(giornalista__dataNascita__gt=data, visualizzazioni__gte=visualizzazioni)

    # Per mettere in OR le condizioni utilizzare l'operatore Q
    from django.db.models import Q
    # 19 ...scrivi quali articoli vengono selezionati
    articoli_con_or = Articolo.objects.filter(Q(giornalista__dataNascita__gt=data) | Q(visualizzazioni__lte=visualizzazioni))

    # Per il NOT (~) utilizzare l'operatore Q
    #20 ...scrivi quali articoli vengono selezionati
    articoli_not = Articolo.objects.filter(~Q(giornalista__dataNascita__lt=data))
    #oppure il metodo exclude
    articoli_not = Articolo.objects.exclude(giornalista__dataNascita__lt=data)


    # Creare il dizionario context
    context = {
        'articoli_cognome': articoli_cognome,
        'numero_totale_articoli': numero_totale_articoli,
        'numero_articoli_giornalista_1': numero_articoli_giornalista_1,
        'articoli_ordinati': articoli_ordinati,
        'articoli_senza_visualizzazioni': articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato': articolo_piu_visualizzato,
        'giornalisti_data': giornalisti_data,
        'articoli_del_giorno': articoli_del_giorno,
        'articoli_periodo': articoli_periodo,
        'articoli_giornalisti': articoli_giornalisti,
        'giornalista_giovane': giornalista_giovane,
        'giornalista_anziano': giornalista_anziano,
        'ultimi': ultimi,
        'articoli_minime_visualizzazioni': articoli_minime_visualizzazioni,
        'articoli_parola': articoli_parola,
        'articoli_mese_anno':articoli_mese_anno,
        'giornalisti_con_articoli_popolari':giornalisti_con_articoli_popolari,
        'articoli_con_and':articoli_con_and,
        'articoli_con_or':articoli_con_or,
        'articoli_not':articoli_not
    }
    return render(request, 'queryBase.html', context)

def listaArticoli(request,pk=None):
    if pk==None:
        articoli= Articolo.objects.all()
    else:
        articoli = Articolo.objects.filter(giornalista_id=pk)
    context={
            "articoli": articoli,
    }
    return render(request, "lista_articoli.html", context)

"""def home(request):
    a=""
    g=""
    for art in Articolo.objects.all():
        a += (art.titolo + "<br>")
    
    for gio in Giornalista.objects.all():
        g += (gio.nome + "<br>")
    response = "Articoli:<br>" + a + "<br>Giornalisti:<br>" + g

    return HttpResponse("<h1> Homepage news! </h1>")
"""
"""
def home(request):
    a=[]
    g=[]
    for art in Articolo.objects.all():
        a.append(art.titolo)
    
    for gio in Giornalista.objects.all():
        g.append(gio.nome)

    response = str(a) + "<br>" + str(g)
    print(response)
    
    return HttpResponse("<h1>"+ response +"</h1>")
"""
def home(request):
    
    articoli=Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti":giornalisti}
    print(context)
    
    return render(request,"homepage_news.html", context)

news/templates/articolo_detail.html
{%extends "base.html"%}

{% block title %} 
    {{ articolo.titolo }}
{% endblock title %}

{%block content%}
    <h1>{{ articolo.titolo }}</h1>
    <h3>{{ articolo.contenuto }}</h3>
    <h5>Autore: {{ articolo.giornalista }}</h5>
{%endblock content%}

news/templates/giornalista_detail.html
{%extends "base.html"%}
{% block title %} 
    Dettagli del giornalista
{% endblock title %}

{%block content%}
    <h1>Dettagli del giornalista: </h1>
    <h3>{{ giornalista.nome }}</h3>
    <h3>{{ giornalista.cognome }}</h3>
    <h5>Nato il {{ giornalista.dataNascita }}</h5>
    <br>
    <h5>Tutti i suoi articoli e visualizzazioni: </h5>

    {% for articolo in articoli %}
        <ul>
            <strong><li>Titolo:</strong>
                <a href="/news/articoli/{{articolo.id}}">{{articolo.titolo}}</a>- n. {{articolo.visualizzazioni}}
            </li>
        </ul>
    {% endfor %}

{%endblock content%}

news/templates/homepage.html
{%extends "base.html"%}
{% block title %} 
    Articoli e Giornalisti
{% endblock title %}
{%block content%}
<h4>Articoli:</h4>
    {% for articolo in articoli %}
        <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
        <hr>
    {% endfor %}
<h4>Giornalisti:</h4>
    {% for articolo in articoli %}
        <p><strong>Nome: </strong>{{ giornalista.nome }}</p>
        <p><strong>Cognome: </strong>{{ giornalista.cognome }}</p>
        <hr>
    {% endfor %}
{%endblock content%}

news/templates/homepage_news.html
{%extends "base.html"%}
{% block title %} 
    Articoli e Giornalisti
{% endblock title %}
{%block content%}
<h4>Articoli:</h4>
    {% for articolo in articoli %}
        <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
        <hr>
    {% endfor %}
<h4>Giornalisti:</h4>
    {% for giornalista in giornalisti %}
        <p><strong>Nome: </strong>{{ giornalista.nome }}</p>
        <p><strong>Cognome: </strong>{{ giornalista.cognome }}</p>
        <hr>
    {% endfor %}
{%endblock content%}

news/templates/index3.html
{%extends "base.html"%}
{% block title %} {{block.super}} Index{% endblock title %}
{%block content%}
        <ol>
            <li><a href="{% url 'news:index_root'%}">Index root</a></li>
            <li><a href="{% url 'news:homeview'%}">Homepage news</a></li>
            <li><a href="{% url 'news:articolo_detail' 1%}">Articolo detail</a></li>
            <li><a href="{% url 'news:giornalista_detail' 5%}">Giornalista detail</a></li>
            <li><a href="{% url 'news:lista_articoli'%}">Lista articoli</a></li>
            <li><a href="{% url 'news:queryBase'%}">Query</a></li>
        </ol>
{%endblock content%}

news/templates/lista_articoli.html
{%extends "base.html"%}

{% block title %} 
    {{block.super}} | Lista articoli 
{% endblock title %}

{%block content%}
    <h4>Lista Articoli: </h4>
    {% for articolo in articoli %}
        <p><strong>Titolo:</strong>
            <a href="/news/articoli/{{articolo.id}}">{{articolo.titolo}}</a>
        </p>
        <p><strong>Contenuto:</strong>
            {{articolo.contenuto}}
        </p>
        <p><strong>Autore:</strong>
            <a href={% url 'news:giornalista_detail' articolo.giornalista.id %}>{{articolo.giornalista}}</a>
        </p>
        <hr>
    {% endfor %}
{%endblock content%}

news/templates/queryBase.html
{% extends "base.html" %}
    {% block title %}QueryBAse{% endblock title %}
    {% block content %}
        {% for articolo in articoli_cognome %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        <h5>Numero articoli: {{numero_totale_articoli}}
        </h5>
        <hr>
    
        <h5>Numero articoli: {{numero_articoli_giornalista_1}}
        </h5>
        <hr>
    
        <h5>articoli senza visualizzazioni</h5>
        {% for articolo in articoli_senza_visualizzazioni %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        <h5>articolo più visualizzato: {{articolo_piu_visualizzato}}</h5>
        <hr>
    
        {% for giornalista in giornalisti_data %}
        <h1>{{giornalista.nome}}</h1>
        <h3>{{giornalista.cognome}}</h3>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_del_giorno %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_periodo %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_giornalisti %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        <h5>Giornalista giovane: </h5>
        <h5>{{giornalista_giovane.nome}}</h5>
        <h5>{{giornalista_giovane.cognome}}</h5>
        <hr>
    
        <h5>Giornalista anziano: </h5>
        <h5>{{giornalista_anziano.nome}}</h5>
        <h5>{{giornalista_anziano.cognome}}</h5>
        <hr>
    
        {% for articolo in ultimi %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_minime_visualizzazioni %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_parola %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_mese_anno %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for giornalista in giornalisti_con_articoli_popolari %}
        <h1>{{giornalista.nome}}</h1>
        <h3>{{giornalista.cognome}}</h3>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_con_and %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_con_or %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    
        {% for articolo in articoli_con_not %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
        {% endfor %}
        <hr>
    {% endblock content %}